version: '3.8'

services:

  coin-glue-dev:
     container_name: "secret-santa"
     hostname: "secret-santa"
     env_file:
       - ./src/.env
     build:
       context: ./src
       dockerfile: ./Dockerfile
     restart: always
     volumes:
       - ./src:/code
     working_dir: /code
     command: ash -c "python main.py"
     depends_on:
       - db-dev

  db-dev:
    container_name: "secret-santa-db"
    hostname: "secret-santa-db"
    image: postgres:15-alpine
    ports:
      - 5472:5432
    env_file:
      - ./src/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/secret_santa:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G