"""init

Revision ID: 063546e9495b
Revises: be608b831378
Create Date: 2024-11-08 23:35:14.648945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063546e9495b'
down_revision = 'be608b831378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'description')
    # ### end Alembic commands ###
