from decouple import config

DEBUG = True
POSTGRES_HOST = config("POSTGRES_HOST")
POSTGRES_PORT = config("POSTGRES_PORT")
POSTGRES_NAME = config("POSTGRES_NAME")
POSTGRES_DB = config("POSTGRES_DB")
POSTGRES_USER = config("POSTGRES_USER")
POSTGRES_PASSWORD = config("POSTGRES_PASSWORD")

API_TOKEN = config("API_TOKEN")

ADMIN_ID = config("ADMIN_ID")

CATALOG_ID = config("CATALOG_ID")
YANDEX_TOKEN = config("YANDEX_TOKEN")
